### ISSUE TITLE
why Listen "/p2p-circuit"?

### ISSUE THREAD

**Issue by zeigo** [libp2p/go-libp2p-circuit#102]
I know `Listen` returns a listener, and when a relay peer sends STOP to my peer, `listener.Accept()` gets a conn. So, when will the conn open a stream or accept a stream? Why construct such a conn?

**Comment by Stebalien** [comment]
Could you expand on that? I'm not sure what you're trying to ask.

**Comment by zeigo** [comment]
Listening "/p2p-circuit" makes  `RelayListener.Accept()` called. If a relay hop opens a stream for circuit relay to peer B, then sends STOP, B will call `handleStopStream`, and write a conn to chan `incoming`. `RelayListener.Accept()` will read this conn from chan `incoming`, send a SUCCESS back, and return the conn.
So, why doesn't `handleStopStream` send SUCCESS directly? What's the conn used for? It seems this issue #28 is about it, but I can't understand it.

**Comment by Stebalien** [comment]
Ah. The "swarm" calls `Accept` [here](https://github.com/libp2p/go-libp2p-swarm/blob/7694d474660c961cd69d3be7ef12342fb275e58b/swarm_listen.go#L84). At that point, the swarm will start accepting multiplexed streams off the connection [here](https://github.com/libp2p/go-libp2p-swarm/blob/7694d474660c961cd69d3be7ef12342fb275e58b/swarm_conn.go#L98).

The circuit transport doesn't use the connections directly, it gives them to go-libp2p-swarm.

Note: #28 is a unrelated.

**Comment by Stebalien** [comment]
FYI, we don't send "SUCCESS" in `handleStopStream` because we haven't _really_ succeeded until the connection is actually accepted by the swarm.
