### ISSUE TITLE
Random Test Failure

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-circuit#12]
I occasionally get the following error when running the tests:

```
--- FAIL: TestFullAddressTransportDial (0.12s)
	transport_test.go:77: dial attempt failed: failed to dial <peer.ID NMJzVN> (default failure)
```

**Comment by vyzo** [comment]
Looks like it didn't make it to the dialer, this error comes from the default dial failure.
Perhaps there is a race with registering the dialer?

**Comment by vyzo** [comment]
yes, it looks like that Test is missing the sleep delay other tests have.

**Comment by vyzo** [comment]
oh nm, there is a delay in testSetupRelay for all tests.

**Comment by Stebalien** [comment]
Personally, I like running tests in parallel to repro issues like this (messes with the scheduler).

```sh
> gx-go rw
> parallel -j7 -i go test -run TestFullAddressTransportDial -- {1..100}
```

**Comment by raulk** [comment]
Closing as a result of spring cleaning. Reopen if this is still a problem.

**Comment by Stebalien** [comment]
I can't reproduce. This may have been fixed with all the connection tracking fixes.
