### ISSUE TITLE
Add "Usage" section to README

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-libp2p-circuit#49]
Please :)

**Comment by raulk** [comment]
@whyrusleeping very kindly contributed this example yesterday: https://github.com/libp2p/go-libp2p-examples/pull/12. We might just make the Usage section point there once it's merged. Thoughts?

**Comment by raulk** [comment]
Fixed in https://github.com/libp2p/go-libp2p-circuit/commit/6d7bba4e9d13dd3af17f805b267fba335efadae0.
