### ISSUE TITLE
What's the difference between `OptActive`, `OptHop` and `OptDiscovery`?

### ISSUE THREAD

**Issue by cannium** [libp2p/go-libp2p-circuit#52]
I can see `OptDiscovery` and `OptHop` are set in `go-ipfs`, but their meanings are ambiguous to me, and the config `cfg.Swarm.DisableRelay` seems not very Orthogonal. Also, `OptActive` seems never used, but there's an error related:
https://github.com/libp2p/go-libp2p-circuit/blob/f83937ed3384bb289ba39ee0c4f428f26013390a/relay.go#L291-L294
Could someone kindly explain the intentions of these options?

**Comment by cannium** [comment]
I recall previously `/p2p-circuit/p2p/xxx` could use a random relay node, is it related to `OptActive`?

**Comment by vyzo** [comment]
No, this is enabled with `OptDiscovery`.
