### ISSUE TITLE
Implicit multiaddr dialing does not try circuit relay

### ISSUE THREAD

**Issue by guysv** [libp2p/go-libp2p-circuit#58]
When attempting to connect an implicit `/ipfs/Qm...` multiaddr, libp2p should fallback to circuit-relay. (I.E. try `/p2p-circuit/ipfs/Qm...`).  
  
As I discovered in [this issue](https://github.com/libp2p/js-libp2p-circuit/issues/46#issuecomment-465746725), only explicit dialing to `/p2p-circuit/ipfs/Qm...` will use a relay.  
  
Am I missing something or this is a bug?

**Comment by Stebalien** [comment]
libp2p will only dial a circuit address if the peer _advertises_ one (or if you _explicitly_ tell libp2p to use a random relay by specifiying `/p2p-circuit/ipfs/Qm...`). That's intended as we generally have no reason to believe that a random relay (not advertised by the target peer) will work better than dialing them directly.

**Comment by Stebalien** [comment]
Take a look at the libp2p AutoRelay option.
