### ISSUE TITLE
Revise the relay protocol

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-circuit#68]
Carried over from https://github.com/libp2p/go-libp2p/pull/578#discussion_r272800535:

A relay client can be a _consumer_ of a relay service, or a _target_ of a relayed connection. Currently, all of these flow over the same thick protocol. I really have a hard time wrapping my head around this, and so do our users.

I'd like to segregate this protocol if possible into at least two:

* `/libp2p/circuit/relay/hop/v0.0.0`: exposed only by relay nodes. Used inside the initiator -> relay connection.
* `/libp2p/circuit/relay/target/v0.0.0`: exposed by clients accepting relayed connections. Used in the relay -> target connection.

This would allow for better implicit observability too. Would've helped a lot in the incident we're analysing.

**Comment by Stebalien** [comment]
https://github.com/libp2p/specs/issues/105

**Comment by raulk** [comment]
Continuing discussion in libp2p/specs#105.
