### ISSUE TITLE
Docs: Do I _certainly_ not want to enable opt.Discovery?

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-libp2p-circuit#92]
```
    // OptDiscovery configures this relay transport to discover new relays
    // by probing every new peer. You almost _certainly_ don't want to
    // enable this.
    OptDiscovery = RelayOpt(2)
```

But this is enabled by default in go-ipfs. Could someone revisit the documentation for the options? There are 3 things that should be explicit:

- What it does? -> i.e. This will allow this peer to discover if other peers are active relays that can be used
- How it does it? -> It does this by probing every new peer to which connections are established to see whether it is an active relay or not (?).
- What are the consenquences? -> Enabling this results in... [what does it do that it's so bad?]

(should be clear for every option). @vyzo is this in your alley? I keep finding myself confused every time I land on these options. The documentation gives recommendations like "knowing what you are doing". If I knew what I'm doing I certainly would not need to read the docs.

**Comment by vyzo** [comment]
We probably want to update the documentation at some point, as we plan to make it useful for autorelay.

Briefly, what it does is that it queries new peers for relay support (using `CanHop`) and keeps them in a list.
Initially it was used to support unspecific relay addrs of the form `/p2p-circuit/p2p/QmFoo`.
We eventually decided that these addresses are a bad idea, but we haven't turned off the option in ipfs.

But as I said, the plan is to start emitting events on discovered relays and utilize those in autorelay for passive relay discovery, which would make the option truly useful.

**Comment by Stebalien** [comment]
You certainly want to remove it and I'm removing it from the code. See #101.

**Comment by hsanjuan** [comment]
Happy! Thanks for getting back here.
